is_windows: "{{ ansible_facts.os_family == 'Windows' }}"
is_container: "{{ '/.dockerenv' is exists }}"
is_wsl: >-
  {{
    (ansible_facts.kernel is search('microsoft', ignorecase=True))
    and (not is_container)
  }}
