is_windows: "{{ ansible_facts.os_family == 'Windows' }}"
is_container: "{{ '/.dockerenv' is exists }}"
is_wsl: >-
  {{
    (ansible_facts.kernel is search('microsoft', ignorecase=True))
    and (not is_container)
  }}
linux_arch: >-
  {{
    (ansible_facts.architecture == 'x86_64') | ternary('amd64',
      (ansible_facts.architecture == 'aarch64') | ternary('arm64', 'unknown')
    )
  }}
