## Gitの全体共通設定
git_configs:
  # コミットメッセージ中のハサミ行以下を除去する（# を残す）
  - name: commit.cleanup
    value: scissors
  # WindowsではCRLFでチェックアウトする。それ以外LFでチェックアウト。
  - name: core.autocrlf
    value: "{{ ansible_facts.distribution.startswith('Microsoft Windows') | ternary('true', 'input') }}"
  - name: core.quotePath
    value: "false"
  - name: merge.conflictStyle
    value: diff3
  - name: merge.ff
    value: "false"
  - name: alias.dry-merge
    value: merge --no-commit --no-ff
