# some more aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'
alias rm='rm -i'
alias vless='/usr/share/vim/vim73/macros/less.sh'
alias lsa='ls -a'
alias lsl='ls -l'
alias lsal='ls -al'
alias xdvi='pxdvi'
alias apti='sudo apt-get install'
alias apts='apt-cache search'
alias e='emacs'
alias ec='emacsclient'
alias tmux='tmux -2'
alias psg='ps aux | grep'
alias go='gnome-open'
alias acroread='UBUNTU_MENUPROXY= LIBOVERLAY_SCROLLBAR=0 acroread'
alias t='tmux attach || tmux'
alias g='git'

echo "Load .bash_aliases."
