- name: Starship for Windows
  tags: [starship]
  when: ansible_facts.os_family == 'Windows'
  block:
    - name: Generate starship config
      tags: [config]
      win_template:
        src: 'starship.toml.j2'
        dest: '{{ ansible_facts.env.USERPROFILE }}\.config\starship.toml'
- name: Starship for other than Windows
  when: ansible_facts.os_family != 'Windows'
  tags: [starship]
  block:
    - name: Generate starship config
      tags: [config]
      template:
        src: 'starship.toml.j2'
        dest: '~/.config/starship.toml'
