- tags: [package]
  block:
    - name: Set a variable for extract directory
      set_fact:
        extract_dir: /tmp/ghq_linux_amd64
    - name: Download a ghq archive
      get_url:
        url: https://github.com/x-motemen/ghq/releases/download/v1.1.5/ghq_linux_amd64.zip
        dest: "{{ extract_dir }}.zip"
        checksum: sha256:417b7a6f71a80cff32e9f61a6578f7ec3b58e0470863ad719760c3fada938e70
      register: download_archive
    - name: Delete the extracted directory if download a new archive
      file:
        path: "{{ extract_dir }}"
        state: absent
      when: download_archive.changed
    - name: Extract the archive
      unarchive:
        src: "{{ extract_dir }}.zip"
        dest: /tmp
        remote_src: yes
        mode: "0700"
    - name: Copy ghq executable
      become: yes
      copy:
        src: "{{ extract_dir }}/ghq"
        remote_src: yes
        dest: /usr/local/bin
        mode: "0755"
    - name: Copy ghq bash completion
      become: yes
      copy:
        src: "{{ extract_dir }}/misc/bash/_ghq"
        remote_src: yes
        dest: /etc/bash_completion.d
        mode: "0644"
