- name: Validate the role precondition
  tags: [validation]
  import_tasks: validate_precondition.yml
- name: Update apt cache
  tags: [package]
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install ansible module requirements
  tags: [package]
  become: yes
  apt:
    name:
      - gpg # for gpg operations
      - xz-utils # for apt related tasks
      - zstd # for apt related tasks
- name: Configure runtime icon
  tags: [config]
  become: yes
  copy:
    src: runtime-icon.sh
    dest: /etc/profile.d/runtime-icon.sh
    mode: "0644"
- name: Keep proxy env for sudo
  tags: [config]
  become: yes
  when: ansible_facts.user_id != 'root'
  copy:
    dest: /etc/sudoers.d/proxy_env
    content: |
      Defaults env_keep += "http_proxy"
      Defaults env_keep += "https_proxy"
      Defaults env_keep += "no_proxy"
    mode: "0440"
- name: Configure pipenv
  # Create a virtualenv for pipenv in the project directory
  tags: [config]
  become: yes
  copy:
    dest: /etc/profile.d/pipenv.sh
    content: export PIPENV_VENV_IN_PROJECT=true
    mode: "0644"
- name: Configure man to install all manuals
  tags: [config]
  become: yes
  file:
    path: /etc/dpkg/dpkg.cfg.d/excludes
    state: absent
- name: Add a gpg key for emacs ppa repository
  import_tasks: add_apt_key.yml
  tags: [package]
  become: yes
  vars:
    apt_key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FF0E01EEAAFC9CD
    apt_keyring_location: /etc/apt/keyrings/ppa-kelleyk-emacs.gpg
    apt_keyring_checksum: 23ba53c5700adc8a149868a44e2c5493a39923a632cf25c8f5a22eca9cf3c2e3
- name: Add an emacs ppa repository
  tags: [package]
  become: yes
  apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/ppa-kelleyk-emacs.gpg]
      http://ppa.launchpad.net/kelleyk/emacs/ubuntu  {{ ansible_facts.distribution_release }} main
    state: present
- name: Uninstall old emacs packages
  tags: [package]
  become: yes
  apt:
    name:
      - emacs26
      - emacs26-common
      - emacs26-el
      - emacs27
      - emacs27-common
      - emacs27-el
    state: absent
- name: Install emacs 28
  tags: [package]
  become: yes
  apt:
    name: emacs28
    state: present
- name: Add a gpg key for docker apt repository
  import_tasks: add_apt_key.yml
  tags: [package]
  become: yes
  vars:
    apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    apt_keyring_location: /etc/apt/keyrings/docker-archive-keyring.gpg
    apt_keyring_checksum: a09e26b72228e330d55bf134b8eaca57365ef44bf70b8e27c5f55ea87a8b05e2
- name: Add a docker apt repository
  tags: [package]
  become: yes
  apt_repository:
    repo: >-
      deb [arch={{ linux_arch }} signed-by=/etc/apt/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
    state: present
- name: Install development packages
  tags: [package]
  become: yes
  apt:
    name:
      - cmigemo
      - connect-proxy
      - curl
      - fonts-ipafont
      - fonts-ipaexfont
      - git
      - info
      - language-pack-ja
      - man-db
      - manpages
      - manpages-dev
      - python3-pip
      - python3-setuptools
      - python3-venv
      - shellcheck
      - tmux
      #- ubuntu-wsl
      - x11-xserver-utils
      - zsh
    state: present
- name: Install development packages on Ubuntu 22.04 or later
  tags: [package]
  become: yes
  when: ansible_facts.distribution_version is version('22.04', '>=')
  apt:
    name:
      - ripgrep
- name: Install utility packages
  tags: [package]
  become: yes
  apt:
    name:
      - socat
- name: Install serverspec dependencies
  tags: [package]
  become: yes
  apt:
    name:
      - build-essential
      - libffi-dev
      - ruby-bundler
      - ruby-dev
    state: present
- name: Install docker CLI
  tags: [package]
  become: yes
  apt:
    name: docker-ce-cli
    state: present
  when: ansible_facts.env.GITHUB_ACTIONS is not defined
- name: Install CLI tools by homebrew
  tags: [package]
  become: false
  community.general.homebrew:
    name:
      - fd
      - ripgrep
      - git-delta
      - bat
      - fzf
      - ghq
    state: present
- include_tasks: install_hackgen.yml
  tags: [package]
  loop:
    - name: HackGen
      version: v2.7.1
      checksum: sha256:ec492a85dae77ff81818e75f775ec03bc391a96cf97c816fed1d221375b7be32
    - name: HackGen_NF
      version: v2.7.1
      checksum: sha256:3c1949682567f8b4d4984c30b1439f051f2062a3138ddbf2262c12d087f60d92
  loop_control:
    loop_var: font
- name: Install pip tools
  tags: [package]
  become: yes
  pip:
    name: pipenv
    executable: pip3
- name: Install node.js 16
  become: yes
  tags: [package]
  block:
    - name: Add a nodesource signing key to a keyring
      import_tasks: add_apt_key.yml
      vars:
        apt_key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        apt_keyring_location: /etc/apt/keyrings/nodesource.gpg
        apt_keyring_checksum: 51034f1b19ccd22fd9b61c516c0226e956b6add3d36ee96b0fb235d598848774
    - name: Add nodesource ppa repository
      apt_repository:
        repo: >
          deb [signed-by=/etc/apt/keyrings/nodesource.gpg]
          https://deb.nodesource.com/node_16.x {{ ansible_facts.distribution_release }} main
        state: present
    - name: Install nodejs 16 package
      apt:
        name: nodejs
        state: present
- name: Set ~/.node as npm prefix
  become: no
  tags: [config]
  shell: 'npm config set prefix ~/.node'
  changed_when: no
- name: Install node tools
  tags: [package]
  become: no
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - prettier
    - textlint
    - textlint-rule-preset-ja-technical-writing
    - textlint-rule-preset-ja-spacing
    - textlint-rule-prh
    - textlint-filter-rule-comments
- name: Create a parent directory of config files
  tags: [config]
  become: no
  file:
    path: "~/{{ item.dest | dirname }}"
    state: directory
    mode: "0755"
  loop: "{{ symlink_config_files }}"
  when: item.condition | default(true)
- name: Link to config files
  tags: [config]
  become: no
  file:
    src: "~/dotfiles/{{ item.src }}"
    path: "~/{{ item.dest }}"
    state: link
    force: yes
  loop: "{{ symlink_config_files }}"
  when: item.condition | default(true)
- name: Create a parent directory of config dirs
  tags: [config]
  become: no
  file:
    path: "~/{{ item.dest | dirname }}"
    state: directory
    mode: "0755"
  loop: "{{ symlink_config_dirs }}"
  when: item.condition | default(true)
- name: Link to config dirs
  tags: [config]
  become: no
  file:
    src: "~/dotfiles/{{ item.src }}"
    path: "~/{{ item.dest }}"
    state: link
    force: yes
  loop: "{{ symlink_config_dirs }}"
  when: item.condition | default(true)
- name: Configure git
  tags: [config]
  become: no
  git_config: "{{ {'scope':'global'} | combine(item) }}" # デフォルトのスコープを global にする
  with_items:
    - "{{ git_configs }} "
    - "{{ _git_configs | default([]) }}"
- name: Add a gpg key for Microsoft
  import_tasks: add_apt_key.yml
  tags: [package]
  become: yes
  vars:
    apt_key_url: https://packages.microsoft.com/keys/microsoft.asc
    apt_keyring_location: /etc/apt/keyrings/microsoft.gpg
    apt_keyring_checksum: b4dcc2fb98c13b5fc96aee6cd7e3c1e82516f57fab40df83f57dfed1820cb981
- name: Add an ppa for Visual Studio Code
  tags: [package]
  become: yes
  apt_repository:
    repo: >-
      deb [arch={{ linux_arch }} signed-by=/etc/apt/keyrings/microsoft.gpg]
      https://packages.microsoft.com/repos/vscode stable main
    state: present
- name: Install Visual Studio Code
  tags: [package]
  become: yes
  apt:
    name: code
