add_newline = false

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[status]
disabled = false
format = '[$symbol$status]($style)  '

[git_status]
disabled = true

# Indicator that proxy is enabled or not
[env_var.http_proxy]
style = '#99FF99'
format = '[PROXY]($style)'
[env_var.https_proxy]
style = '#7bdcfe'
format = '[S]($style) '

[aws]
symbol = " "
force_display = true
[aws.region_aliases]
ap-northeast-1 = "Tokyo"
