add_newline = false

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[status]
disabled = false
format = '[$symbol$status]($style)  '

[git_status]
disabled = true

[python]
pyenv_version_name = true

[env_var]
variable = 'RUNTIME_ICON'
default = 'Unknown Runtime'
style = '#ff9900'
format = 'on [$env_value]($style) '
