add_newline = false

[character]
{{#if (eq dotter.os "unix")}}
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
{{else}}
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
{{/if}}

[status]
disabled = false
format = '[$symbol$status]($style)  '

[git_status]
disabled = true

# Indicator that proxy is enabled or not
[env_var.http_proxy]
style = '#99FF99'
format = '[PROXY]($style)'
[env_var.https_proxy]
style = '#7bdcfe'
format = '[S]($style) '

[aws]
symbol = " "
force_display = true
[aws.region_aliases]
ap-northeast-1 = "Tokyo"

{{#if (eq dotter.os "unix")}}
[env_var.RUNTIME_ICON]
default = 'Unknown Runtime'
style = '#ff9900'
format = 'on [$env_value]($style) '
{{/if}}

# シェルのインジケーターを表示する
[shell]
format = '[$indicator]($style)'
bash_indicator = ""
powershell_indicator = "PS"
unknown_indicator = '?'
disabled = false
