- name: Configure wsl.conf
  copy:
    dest: /etc/wsl.conf
    content: |
      [automount]
      enabled = true
      root = /mnt/
      options = "metadata,umask=22,fmask=11"
      mountFsTab = true
- name: Configure umask for wsl file systems
  copy:
    dest: /etc/profile.d/umask.sh
    content: umask 022
- name: Integrate with ssh-agent-wsl
  copy:
    dest: /etc/profile.d/ssh-agent-wsl.sh
    content: |
      if which ssh-agent-wsl > /dev/null 2>&1; then
        eval "$(ssh-agent-wsl -r)"
      fi
- name: Configure man to install all manuals
  file:
    path: /etc/dpkg/dpkg.cfg.d/excludes
    state: absent
- name: Add a gpg key for emacs ppa repository
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FF0E01EEAAFC9CD
    state: present
- name: Add an emacs ppa repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/kelleyk/emacs/ubuntu  {{ ansible_facts.distribution_release }} main
    state: present
- name: Install development packages
  apt:
    name:
      - cmigemo
      - connect-proxy
      - curl
      - emacs26
      - git
      - language-pack-ja
      - man
      - nodejs
      - npm
      - tmux
      - x11-xserver-utils
      - zsh
    state: present
    update_cache: yes
- name: Install serverspec dependencies
  apt:
    name:
      - build-essential
      - libffi-dev
      - ruby-bundler
      - ruby-dev
    state: present
- name: Remove unnecessary packages
  package:
    name:
      - openssh-server
    state: absent
- name: Add a gpg key for docker apt repository
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add a docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
    state: present
- name: Install docker CLI
  apt:
    name: docker-ce-cli
    state: present
    update_cache: yes
- name: Add a gpg key for wslu
  apt_key:
    url: https://packagecloud.io/whitewaterfoundry/wslu/gpgkey
    state: present
- name: Add a wslu apt repository
  apt_repository:
    repo: deb https://packagecloud.io/whitewaterfoundry/wslu/ubuntu/ {{ ansible_facts.distribution_release }} main
    state: present
- name: Install wslu
  apt:
    name: wslu
    state: present
    update_cache: yes
- name: Check if ripgrep is installed
  command: dpkg-query -W ripgrep
  register: my_ripgrep_installed
  failed_when: my_ripgrep_installed.rc > 1
  changed_when: my_ripgrep_installed.rc == 1
- name: Download a ripgrep debian package
  get_url:
    url: https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb
    dest: /tmp/ripgrep_0.10.0_amd64.deb
  when: my_ripgrep_installed.changed
- name: Install a ripgrep package
  apt: deb="/tmp/ripgrep_0.10.0_amd64.deb"
  when: my_ripgrep_installed.changed
- name: Install node tools
  npm:
    name: prettier
    global: yes
- name: Configure git
  become: no
  git_config:
    name: core.autocrlf
    scope: global
    value: input
- name: 手っ取り早くシェル実行
  become: no
  # ansibleモジュールでの書き方がわからないところを無理やりシェルで解決するコーナー
  shell: |
    # Windows側のGit設定を引き継ぐ
    git config --global user.name "$(cmd.exe /C git config --global user.name)"
    git config --global user.email "$(cmd.exe /C git config --global user.email)"
