- tags: [configuration]
  block:
    - name: 設定ファイルのパスを絶対パス展開
      set_fact:
        config_src_path: '{{ ansible_facts.env.USERPROFILE }}\dotfiles\{{ config_file.src }}'
        config_dest_path: '{{ ansible_facts.env.USERPROFILE }}\{{ config_file.dest }}'
    - name: '"{{ config_file.dest }}"の状態を確認する'
      win_stat:
        path: "{{ config_dest_path }}"
      register: config_dest
    - name: '"{{ config_file.dest }}"を削除する'
      win_file:
        path: "{{ config_dest_path }}"
        state: absent
      # リンク先が存在するがシンボリックリンクでなかったり、リンク元が異なる場合は一旦削除する
      when:
        - config_dest.stat.exists
        - (not config_dest.stat.islnk) or (config_dest.stat.lnk_source != config_src_path)
      register: del_config_dest
    - name: '"{{ config_file.src }}"のシンボリックリンクをはる'
      win_shell: 'mklink "{{ config_dest_path }}" "{{ config_src_path }}"'
      args:
        executable: cmd
      when: not config_dest.stat.exists or del_config_dest.changed
