- tags: [config]
  block:
    - name: 設定ディレクトリのパスを絶対パス展開
      set_fact:
        config_src_path: '{{ ansible_facts.env.USERPROFILE }}\dotfiles\{{ config_dir.src | regex_replace("/", "\\") }}'
        config_dest_path: '{{ ansible_facts.env.USERPROFILE }}\{{ config_dir.dest | regex_replace("/", "\\") }}'
    - name: '"{{ config_dir.dest }}"の状態を確認する'
      win_stat:
        path: "{{ config_dest_path }}"
        get_checksum: no
      register: config_dest
    - name: '"{{ config_dir.dest }}"の親ディレクトリを作成する'
      win_file:
        path: "{{ config_dest_path | win_dirname }}"
        state: directory
      when: not config_dest.stat.exists
    - name: '"{{ config_dir.dest }}"を削除する'
      win_file:
        path: "{{ config_dest_path }}"
        state: absent
      # リンク先が存在するがシンボリックリンクでなかったり、リンク元が異なる場合は一旦削除する
      when:
        - config_dest.stat.exists
        - (not config_dest.stat.islnk) or (config_dest.stat.lnk_source != config_src_path)
      register: del_config_dest
    - name: '"{{ config_dir.src }}"のシンボリックリンクをはる'
      win_shell: 'mklink /d "{{ config_dest_path }}" "{{ config_src_path }}"'
      args:
        executable: cmd
      when: not config_dest.stat.exists or del_config_dest.changed
