- name: 環境変数を設定する
  tags: [configuration]
  win_environment:
    level: user
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: "EDITOR", value: "emacsclient" }
    - {
        name: "FZF_DEFAULT_OPTS",
        value: '--reverse --inline-info --bind "ctrl-k:kill-line,ctrl-m:accept,ctrl-v:page-down,alt-v:page-up"',
      }
    - { name: "HOME", value: "{{ ansible_facts.env.USERPROFILE }}" }
    - { name: "LANG", value: "ja_JP.UTF-8" }
    - { name: "MSYS", value: "winsymlinks:nativestrict" }
    - { name: "MSYS2_PATH_TYPE", value: "inherit" }
    - { name: "VAGRANT_DEFAULT_PROVIDER", value: "hyperv" }
    - {
        name: "MY_CMDER_CONFIG",
        value: "{{ ansible_facts.env.USERPROFILE }}\\.cmder\\config",
      }
    # ref. https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/
    - { name: "WSLENV", value: "USERPROFILE/p:http_proxy:https_proxy:no_proxy" }
- name: 設定ファイルのシンボリックリンクをはる
  tags: [configuration]
  include_tasks: link_config_file.yml
  with_items:
    - { src: ".bash_aliases", dest: ".bash_aliases" }
    - { src: ".bashrc", dest: ".bashrc" }
    - { src: ".profile", dest: ".profile" }
    - { src: ".profile", dest: ".zprofile" }
    - { src: ".tmux.conf", dest: ".tmux.conf" }
    - { src: ".zsh_aliases", dest: ".zsh_aliases" }
    - { src: ".zshrc", dest: ".zshrc" }
    - { src: "dot.ahk", dest: "dot.ahk" }
    - { src: "dot.nodoka", dest: "dot.nodoka" }
  loop_control:
    loop_var: config_file
- name: ssh-agentサービスを有効にする
  tags: [service]
  win_service:
    name: ssh-agent
    start_mode: delayed
    state: started
- name: OpenSSHサーバのサービスを確実に削除する
  tags: [service]
  win_service:
    name: "{{ item }}"
    state: absent
    dependency_action: remove
  with_items:
    - sshproxy
    - sshbroker
- name: clink_inputrcをコピーする
  # シンボリックリンクが動作しないので仕方ないがコピーですます
  # ref. https://github.com/mridgers/clink/issues/461
  tags: [configuration]
  win_copy:
    src: '%USERPROFILE%\dotfiles\clink_inputrc'
    dest: '%USERPROFILE%\clink_inputrc'
    remote_src: True
- name: ローカルツールディレクトリを作成する
  tags: [configuration]
  win_file:
    path: '%USERPROFILE%\.local\bin'
    state: directory
- name: ローカルツールディレクトリにパスを通す
  tags: [configuration]
  win_path:
    scope: user
    elements: '%USERPROFILE%\.local\bin'
    state: present
- name: 設定ディレクトリのシンボリックリンクをはる
  tags: [configuration]
  include_tasks: link_config_dir.yml
  with_items:
    - { src: ".zsh.d", dest: ".zsh.d" }
    - { src: "utils", dest: "utils" }
  loop_control:
    loop_var: config_dir
- name: utilsディレクトリのパスを通す
  tags: [configuration]
  win_path:
    scope: user
    elements:
      - '%USERPROFILE%\utils'
    state: present
- name: 自作パッケージ用のChocolateyソースを追加する
  tags:
    - package
  win_chocolatey_source:
    name: kai2nenobu
    state: present
    source: https://www.myget.org/F/kai2nenobu
- name: Chocolateyパッケージをインストールする
  tags:
    - package
  win_chocolatey:
    name:
      - 1password4
      - 7zip
      - a5m2
      - adoptopenjdk
      - adoptopenjdk11
      - adoptopenjdk8
      - autohotkey.portable
      - cmdermini
      - cmigemo
      - emacs
      - Firefox
      - fzf
      - git
      - GoogleChrome
      - GoogleJapaneseInput
      - gradle
      - graphviz
      - jq
      - lxrunoffline
      - nkf
      - peco
      - sakuraeditor
      - Sudo
      - vcxsrv
      - vscode
      - winmerge
      - zoomit
    state: latest
- name: Chocolateyパッケージをインストールする（依存除く）
  tags:
    - package
  # 依存パッケージを一緒にインストールすると問題があるパッケージたちは
  # 別途インストールする。
  win_chocolatey:
    name:
      - plantuml
      - spring-boot-cli
    state: latest
    ignore_dependencies: true
- name: プレリリースパッケージをお試しする
  tags: [package]
  win_chocolatey:
    name:
      - mozc-emacs-helper
    allow_prerelease: yes
    state: latest
- name: 自動起動スクリプトを作成する
  tags: [startup]
  vars:
    startup_folder: '%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup'
  win_shortcut: "{{item}}"
  with_items:
    - description: VcXsrvを起動する
      src: 'C:\Program Files\VcXsrv\vcxsrv.exe'
      args: "-multiwindow"
      dest: '{{ startup_folder }}\Auto Start VcXsrv.lnk'
    - description: ユーザAHKスクリプトを起動する
      src: 'C:\ProgramData\chocolatey\bin\AutoHotkey.exe'
      args: '%USERPROFILE%\dot.ahk'
      dest: '{{ startup_folder }}\User AHK.lnk'
## TODO: Cmderを /C オプション付きで起動するショートカット or タスクバーアイコンを
##   作成するタスクが必要。
- name: Cmderのユーザ個別設定ディレクトリを作成する
  # ref. https://github.com/cmderdev/cmder/blob/master/README.md#shared-cmder-install-with-non-portable-individual-user-config
  tags: [configuration, cmder]
  win_file:
    path: "%MY_CMDER_CONFIG%"
    state: directory
- name: Cmderの設定をコピーする
  tags: [configuration, cmder]
  win_copy:
    src: '%USERPROFILE%\dotfiles\cmder\{{ item }}'
    dest: '%MY_CMDER_CONFIG%\{{ item }}'
    remote_src: True
  with_items:
    - prompt.lua
    - settings
    - user-ConEmu.xml
    - user_aliases.cmd
    - user_profile.cmd
- name: 「Emacsで開く」をコンテキストメニューに追加する
  tags: [registry]
  import_tasks: emacs_context_menu.yml
- name: ssh-agent-wslをダウンロードする
  tags: [package]
  win_get_url:
    url: https://github.com/rupor-github/ssh-agent-wsl/releases/download/v2.2/ssh-agent-wsl.7z
    dest: '%TEMP%\ssh-agent-wsl.7z'
    force: yes # Download everytime
    proxy_url: "{{ (proxy_env | default({})).https_proxy | default(omit) }}"
- name: ssh-agent-wslをローカルツールディレクトリに配置する
  tags: [package]
  win_shell: '7z e -aoa "-o%USERPROFILE%\.local\bin" "%TEMP%\ssh-agent-wsl.7z"'
  args:
    executable: cmd
- name: playbook適用日時を保存する
  win_copy:
    dest: C:\ansible_applied.txt
    content: "{{ ansible_facts.date_time.iso8601 }}"
