- name: Validate OS distribution (support only Windows)
  assert:
    that: ansible_facts.distribution is search("Windows")
    fail_msg: '"{{ ansible_facts.distribution }}" is not a supported OS.'
- name: Validate OS version (support only Windows (Server) 1803 or later)
  assert:
    that: ansible_facts.distribution_version is version('10.0.17134.0', '>=')
    fail_msg: '"{{ ansible_facts.distribution_version }}" is not a supported version.'
- name: Validate powershell version (support only version 5 or later)
  assert:
    that: ansible_facts.powershell_version >= 5
    fail_msg: '"{{ ansible_facts.powershell_version }}" is not a supported powershell version.'
