- hosts: all
  vars_files:
    - private_vars.yml
  tasks:
    - name: dotfilesにシンボリックリンクをはる
      win_shell: 'if not exist "{{ item.dest }}" mklink "{{ item.dest }}" "dotfiles\{{ item.path }}"'
      args:
        executable: cmd
        chdir: "%USERPROFILE%"
      with_items:
        - { path: ".bash_aliases", dest: ".bash_aliases" }
        - { path: ".bashrc", dest: ".bashrc" }
        - { path: ".profile", dest: ".profile" }
        - { path: ".profile", dest: ".zprofile" }
        - { path: ".tmux.conf", dest: ".tmux.conf" }
        - { path: ".zsh_aliases", dest: ".zsh_aliases" }
        - { path: ".zshrc", dest: ".zshrc" }
        - { path: "dot.ahk", dest: "dot.ahk" }
    - name: dotfilesにディレクトリのシンボリックリンクをはる
      win_shell: 'if not exist "{{ item.dest }}" mklink /d "{{ item.dest }}" "dotfiles\{{ item.path }}"'
      args:
        executable: cmd
        chdir: "%USERPROFILE%"
      with_items:
        - { path: ".zsh.d", dest: ".zsh.d" }
        - { path: "utils", dest: "utils" }
    - name: 自作パッケージ用のChocolateyソースを追加する
      win_chocolatey_source:
        name: kai2nenobu
        state: present
        source: https://www.myget.org/F/kai2nenobu
    - name: Chocolateyパッケージをインストールする
      win_chocolatey:
        name:
          - 1password4
          - 7zip
          - a5m2
          - adoptopenjdk
          - adoptopenjdk8
          - cmdermini
          - cmigemo
          - emacs
          - Firefox
          - git
          - GoogleChrome
          - GoogleJapaneseInput
          - gradle
          - graphviz
          - jq
          - mape
          - nkf
          - peco
          - sakuraeditor
          - Sudo
          - vscode
          - winmerge
          - zoomit
        state: latest
    - name: Chocolateyパッケージをインストールする（依存除く）
      # 依存パッケージを一緒にインストールすると問題があるパッケージたちは
      # 別途インストールする。
      win_chocolatey:
        name:
          - plantuml
          - spring-boot-cli
        state: latest
        ignore_dependencies: true
    - name: playbook適用日時を保存する
      win_copy:
        dest: C:\ansible_applied.txt
        content: "{{ ansible_date_time.iso8601 }}"
