- hosts: all
  vars_files:
    - private_vars.yml
  tasks:
    - name: 設定ファイルのシンボリックリンクをはる
      tags: [configuration]
      include_tasks: tasks/link_config_file.yml
      with_items:
        - { src: ".bash_aliases", dest: ".bash_aliases" }
        - { src: ".bashrc", dest: ".bashrc" }
        - { src: ".profile", dest: ".profile" }
        - { src: ".profile", dest: ".zprofile" }
        - { src: ".tmux.conf", dest: ".tmux.conf" }
        - { src: ".zsh_aliases", dest: ".zsh_aliases" }
        - { src: ".zshrc", dest: ".zshrc" }
        - { src: "dot.ahk", dest: "dot.ahk" }
      loop_control:
        loop_var: config_file
    - name: dotfilesにディレクトリのシンボリックリンクをはる
      tags:
        - configuration
      win_shell: 'rmdir "{{ item.dest }}" && mklink /d "{{ item.dest }}" "dotfiles\{{ item.path }}"'
      args:
        executable: cmd
        chdir: "%USERPROFILE%"
      with_items:
        - { path: ".zsh.d", dest: ".zsh.d" }
        - { path: "utils", dest: "utils" }
    - name: 自作パッケージ用のChocolateyソースを追加する
      tags:
        - package
      win_chocolatey_source:
        name: kai2nenobu
        state: present
        source: https://www.myget.org/F/kai2nenobu
    - name: Chocolateyパッケージをインストールする
      tags:
        - package
      win_chocolatey:
        name:
          - 1password4
          - 7zip
          - a5m2
          - adoptopenjdk
          - adoptopenjdk8
          - cmdermini
          - cmigemo
          - emacs
          - Firefox
          - git
          - GoogleChrome
          - GoogleJapaneseInput
          - gradle
          - graphviz
          - jq
          - mape
          - nkf
          - peco
          - sakuraeditor
          - Sudo
          - vscode
          - winmerge
          - zoomit
        state: latest
    - name: Chocolateyパッケージをインストールする（依存除く）
      tags:
        - package
      # 依存パッケージを一緒にインストールすると問題があるパッケージたちは
      # 別途インストールする。
      win_chocolatey:
        name:
          - plantuml
          - spring-boot-cli
        state: latest
        ignore_dependencies: true
    - name: Cmder(mini)の設定をコピーする
      tags:
        - configuration
      win_copy:
        src: '%USERPROFILE%\dotfiles\cmder\{{ item }}'
        dest: '%ChocolateyToolsLocation%\cmdermini\config\{{ item }}'
        remote_src: True
      with_items:
        - prompt.lua
        - settings
        - user_aliases.cmd
        - user_profile.cmd
    - name: playbook適用日時を保存する
      win_copy:
        dest: C:\ansible_applied.txt
        content: "{{ ansible_date_time.iso8601 }}"
