- hosts: windows10
  environment: "{{ proxy_env | default({}) }}"
  pre_tasks:
    - name: chocolateyの終了コードを無視するワークアラウンド
      # ref. https://github.com/ansible/ansible/issues/53860#issuecomment-473431360
      tags: [always]
      win_chocolatey_feature:
        name: useEnhancedExitCodes
        state: disabled
  roles:
    - role: local-proxy
      when: local_proxy_type is defined
    - windows10
- hosts: wsl
  become: yes
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - wsl
