- hosts: windows10
  environment: "{{ proxy_env | default({}) }}"
  pre_tasks:
  roles:
    - role: local-proxy
      when: local_proxy_type is defined
    - windows10
- hosts: wsl
  become: yes
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - wsl
