- hosts: windows10
  environment: "{{ proxy_env | default({}) }}"
  tasks:
    - import_role: name=local-proxy
      when: local_proxy_type is defined
    - import_role: name=windows10
- hosts: wsl
  become: yes
  environment: "{{ proxy_env | default({}) }}"
  tasks:
    - import_role: name=wsl
