- hosts: windows10
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: local_proxy
      when: local_proxy_type is defined
    - windows10
  tasks:
    - import_role:
        name: company
      when: lookup("env", "ANSIBLE_MY_PROFILE") == "company"
- hosts: wsl
  become: yes
  environment: "{{ proxy_env | default({}) }}"
  pre_tasks:
    - name: Configure proxy
      tags: [always]
      set_fact:
        proxy_env:
          http_proxy: "http://{{ lookup('env','WSL_GATEWAY') }}:8888"
          https_proxy: "http://{{ lookup('env','WSL_GATEWAY') }}:8888"
          no_proxy: "localhost,127.0.0.1"
      when: wsl_use_host_proxy
  roles:
    - dev_ubuntu
    - wsl
  tasks:
    - import_role:
        name: company
      when: lookup("env", "ANSIBLE_MY_PROFILE") == "company"
