- hosts: windows
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: local_proxy
      when: local_proxy_type is defined
    - windows
- hosts: wsl
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:{{ ansible_env.PATH }}"
    http_proxy: "{{ proxy_env.http_proxy | default('') }}"
    https_proxy: "{{ proxy_env.https_proxy | default('') }}"
  pre_tasks:
    - name: Configure proxy
      tags: [always]
      set_fact:
        proxy_env:
          http_proxy: "http://{{ lookup('env','WSL_GATEWAY') }}:8888"
          https_proxy: "http://{{ lookup('env','WSL_GATEWAY') }}:8888"
          no_proxy: "localhost,127.0.0.1"
      when: wsl_use_host_proxy | default(false)
  roles:
    - role: wsl
      when: is_wsl
    - role: markosamuli.linuxbrew
      vars:
        #linuxbrew_home: /home/linuxbrew
        linuxbrew_use_installer: true
        linuxbrew_init_shell: false
    - dev_ubuntu
