- hosts: all
  become: true
  environment: "{{ proxy_env | default({}) }}"
  tasks:
    - name: Add emacs ppa repository
      apt_repository:
        repo: ppa:kelleyk/emacs
        state: present
    - name: Install development packages
      package:
        name:
          - cmigemo
          - emacs26
          - git
          - tmux
          - zsh
          - x11-xserver-utils
        state: present
    - name: Add a docker apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Add a gpg key for docker apt repository
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Install docker CLI
      package:
        name: docker-ce-cli
        state: present
    - name: Configure git
      git_config:
        name: core.autocrlf
        scope: global
        value: input
