[helpers]

[default]
depends = []

[default.files]
"configs/.bash_aliases" = "~/.bash_aliases"
"configs/.bashrc" = "~/.bashrc"
"configs/.bash.d" = { target = "~/.bash.d", type = "symbolic", recurse = false }
"configs/.profile" = "~/.profile"
"configs/.textlintrc" = "~/.textlintrc"
"configs/.prh.yml" = "~/.prh.yml"
"configs/.tmux.conf" = "~/.tmux.conf"
"configs/navi/config.win.yaml" = "~/AppData/Roaming/navi/config.yaml"
"configs/navi/cheats" = { target = "~/AppData/Roaming/navi/cheats/dotfiles", type = "symbolic", recurse = false }
"configs/bat/config" = "~/AppData/Roaming/bat/config"
"configs/dot.ahk" = "~/dot.ahk"
"configs/dot.nodoka" = "~/dot.nodoka"
"configs/pet/snippet.toml" = "~/AppData/Roaming/pet/snippet.toml"
"configs/wt/settings.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
"configs/profile.ps1" = "~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"
"configs/ps_alias.ps1" = "~/Documents/WindowsPowerShell/ps_alias.ps1"
"configs/pscore_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"configs/vscode/settings.json" = "~/AppData/Roaming/Code/User/settings.json"
"configs/vscode/keybindings.json" = "~/AppData/Roaming/Code/User/keybindings.json"
"configs/starship.win.toml" = "~/.config/starship.toml"
"configs/.wezterm.lua" = "~/.wezterm.lua"
"configs/git/hooks" = { target = "~/.config/git/hooks", type = "symbolic", recurse = false }
"configs/xkb" = { target = ".config/xkb", type = "symbolic", recurse = false }
"utils" = { target = "~/utils", type = "symbolic", recurse = false }

[default.variables]
