[default.files]
"configs/navi/cheats" = { target = "~/AppData/Roaming/navi/cheats/dotfiles", type = "symbolic", recurse = false }
"configs/bat/config" = "~/AppData/Roaming/bat/config"
"configs/pet/snippet.toml" = "~/AppData/Roaming/pet/snippet.toml"
"configs/wt/settings.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
"configs/profile.ps1" = "~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"
"configs/ps_alias.ps1" = "~/Documents/PowerShell/ps_alias.ps1"
"configs/pscore_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"configs/vscode/settings.json" = "~/AppData/Roaming/Code/User/settings.json"
"configs/vscode/keybindings.json" = "~/AppData/Roaming/Code/User/keybindings.json"
