style:
  tag:
    color: cyan
  comment:
    color: yellow
  snippet:
    color: green

finder:
  command: fzf # equivalent to the --finder option

#cheats:
  #path: /home/user/dotfiles/configs/navi:/home/user/.local/share/navi/cheats

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option
