style:
  tag:
    color: cyan
    width_percentage: 15
    min_width: 10
  comment:
    color: yellow
    width_percentage: 40
  snippet:
    color: green

finder:
  command: fzf # equivalent to the --finder option

#cheats:
  #path: /home/user/dotfiles/configs/navi:/home/user/.local/share/navi/cheats

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: cmd.exe
