# Gitリポジトリをクローンするタスク
- tags: [git]
  block:
    - name: 変数設定
      set_fact:
        repo: https://github.com/kai2nenobu/dotfiles.git
        dest: '{{ ansible_facts.env.USERPROFILE }}\dotfiles'
        remote: origin
        refspec: main
    - name: リポジトリをクローンする
      win_command: |
        git clone --origin "{{ remote }}"--branch "{{ refspec }}" -- "{{ repo }}" "{{ dest }}"
      args:
        creates: "{{ dest }}"
    - name: "{{ refspec }}の最新をプルする"
      win_command: |
        git pull --rebase "{{ remote }}" "{{ refspec }}"
      args:
        chdir: "{{ dest }}"
      register: result
      changed_when: "'is up to date' not in result.stdout"
