name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Lint Files
        run: make lint
  vm-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run the bootstrap script
        run: bash -e bootstrap.sh
      - name: Generate a vault password
        run: tr -dc A-Za-z0-9 < /dev/urandom | head -c 32 > ~/.ansible_vault_pass
      - name: Apply ansible playbook
        run: ansible-playbook -i localhost, test.yml
        working-directory: ansible
  container-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run the bootstrap script
        run: docker run -v "$PWD:/mnt" -w /mnt ubuntu:18.04 bash -e bootstrap.sh
