name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.4'
      - name: Create poetry virtualenv
        run: poetry install
        working-directory: ansible
      - name: Lint
        run: make lint
  vm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-18.04']
    steps:
      - uses: actions/checkout@v2
      - name: Copy dotfiles
        run: cp -vr "${{ github.workspace }}" ~
      - name: Run the bootstrap script
        run: bash -e bootstrap.sh
      - name: Apply ansible playbook
        run: . /opt/ansible-venv/bin/activate && cd ~/dotfiles/ansible && ansible-playbook -i test_hosts.ini site.yml --limit wsl
      - name: Apply ansible playbook again
        run: . /opt/ansible-venv/bin/activate && cd ~/dotfiles/ansible && ansible-playbook -i test_hosts.ini site.yml --limit wsl
  container:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image: ['ubuntu:20.04', 'ubuntu:18.04']
    steps:
      - uses: actions/checkout@v2
      - name: Launch a target container
        run: >-
          docker run -d --name target --init -v "$PWD:/root/dotfiles" -w /root/dotfiles
          ${{ matrix.image }} tail -f
      - name: Run the bootstrap script
        run: docker exec target bash -c "./bootstrap.sh"
      - name: Apply ansible playbook
        run: >-
          docker exec target bash -c
          ". /opt/ansible-venv/bin/activate && cd ansible && ansible-playbook -i test_hosts.ini site.yml --limit wsl"
      - name: Apply ansible playbook again
        run: >-
          docker exec target bash -c
          ". /opt/ansible-venv/bin/activate && cd ansible && ansible-playbook -i test_hosts.ini site.yml --limit wsl"
      - name: Kill the target container
        run: docker rm --force target
  windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: wsl
            distribution: Ubuntu-20.04
          - group: wsl
            distribution: Ubuntu-18.04
          - group: windows
            distribution: Ubuntu-20.04
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: actions/checkout@v2
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distribution }}
          set-as-default: 'true'
          wsl-shell-user: wsl
          additional-packages: openssh-client
      - name: Enable no password sudo by user
        shell: cmd
        run: >-
          wsl.exe --user root bash -c "echo 'wsl ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
      - name: Generate a ssh key pair in WSL
        run: |
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
        if: ${{ matrix.group == 'windows' }}
      - name: Setup Windows SSH Server
        shell: powershell
        run: |
          # Install SSH Server
          choco install --no-progress -y openssh --params "/SSHServerFeature"
          # Register a authorized key
          (wsl.exe -- cat /home/wsl/.ssh/id_rsa.pub) -join "`n" `
            | % { [Text.Encoding]::UTF8.GetBytes($_) } `
            | Set-Content -Path 'C:\ProgramData\ssh\administrators_authorized_keys' -Encoding Byte
          # Repair permissions for authorized key file
          icacls 'C:\ProgramData\ssh\administrators_authorized_keys' /inheritance:d
          icacls 'C:\ProgramData\ssh\administrators_authorized_keys' /remove 'NT AUTHORITY\Authenticated Users'
          icacls 'C:\ProgramData\ssh\administrators_authorized_keys'
          Restart-Service -Name sshd -Force
        if: ${{ matrix.group == 'windows' }}
      - name: Copy dotfiles
        run: umask 0022 && mkdir -p ~/dotfiles && cp -vr . ~/dotfiles
      - name: Copy dotfiles in Windows
        shell: powershell
        run: Copy-Item -Recurse . "$env:USERPROFILE"
        if: ${{ matrix.group == 'windows' }}
      - name: Run the bootstrap script
        run: ./bootstrap.sh
      - name: Apply ansible playbook
        run: . /opt/ansible-venv/bin/activate && cd ~/dotfiles/ansible && ansible-playbook -i test_hosts.ini site.yml --limit ${{ matrix.group }}
      - name: Apply ansible playbook again
        run: . /opt/ansible-venv/bin/activate && cd ~/dotfiles/ansible && ansible-playbook -i test_hosts.ini site.yml --limit ${{ matrix.group }}
