name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vm-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the bootstrap script
        run: bash -eu bootstrap.sh
  container-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the bootstrap script
        run: docker run ubuntu:18.04 bash -eu bootstrap.sh
