name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Files
        run: make lint
  vm-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the bootstrap script
        run: bash -e bootstrap.sh
  container-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the bootstrap script
        run: docker run -v "$PWD:/mnt" -w /mnt ubuntu:18.04 bash -e bootstrap.sh
