name: github pages

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "ci/create_ansible_venv.sh"
      - "ansible/pyproject.toml"
      - "ansible/poetry.lock"
      - ".github/workflows/pages.yml"
  workflow_dispatch: # run manually

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  create-venv:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: ["ubuntu-22.04", "ubuntu-20.04", "ubuntu-18.04"]
    steps:
      - uses: actions/checkout@v3
      - name: Create venv in docker
        run: |
          set -eux
          image=$(echo '${{ matrix.image }}' | tr '-' ':')
          docker run -e LANG=C.UTF-8 -v "$PWD:/root/dotfiles" -w /root/dotfiles \
            "$image" ./ci/create_ansible_venv.sh
      - name: Upload the venv archive as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.image }}
          path: "*.tar.gz"
          retention-days: 1
  deploy:
    runs-on: ubuntu-20.04
    needs: create-venv
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs
          destination: _site
      - name: Fix _site owners
        # https://github.com/actions/jekyll-build-pages/issues/18
        run: sudo chown -R runner:docker _site
      - name: Download venv archives
        uses: actions/download-artifact@v3
        with:
          path: /tmp
      - name: Move archives into docs directory
        run: |
          ls -alh _site/
          mkdir -p _site/venv
          find /tmp -type f -name "*.tar.gz" -print0 | xargs -0 mv -t _site/venv
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
